sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

notifications:
  email:
    - jared.starin@alphapoint.com

before_script:
  - echo "in here"
  - echo "building all docker images..."
  - echo "pushing images to container registry"
  # - docker build -t ubiq-client ./ubiq-client
  # - docker build -t ubiq-node ./ubiq-client
  # - docker tag apdocker


script: 
  - echo "running tests"


after_script:
  - echo "about to deploy to K8 cluster "

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
