sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

notifications:
  email:
    - jared.starin@alphapoint.com

before_script:
  - echo "in here"
  # - docker build -t ubiq-client ./ubiq-client
  # - docker build -t ubiq-node ./ubiq-client
  # - docker tag apdocker


script: 
  - echo "running tests"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
