sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

notifications:
  email:
    - jared.starin@alphapoint.com

before_script:
  - echo "in here"

script: 
  - echo "now here"

# deploy:
#   provider: script
#   script: bash ./deploy.sh
#   on:
#     branch: master
