sudo: required

language: node_js

cache:
  directories:
  - node_modules

services:
  - docker

node_js:
  - "8"

notifications:
  email:
    - jared.starin@alphapoint.com

before_install:
  - echo "in here"

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
